# Setup
permalink:        pretty
markdown: kramdown
# relative_permalinks: true
title:            Digital Publisher Guide
tagline:          'Help for publishers and students of publishing'
description:      'tutorials and screencasts about digital publishing and eBook Production'
url:              publisha.github.io
baseurl: ''
twitter_username: pageboy
github_username:  pageboy

author:
  name:           'Chris Jennings'
  url:            https://twitter.com/pageboy

paginate:         5
paginate_path: '/blog/page:num/'
# Custom vars
version:          0.095

github:
  repo:           https://github.com/publisha/publisha.github.io

prose:
  media: 'images'

  # Gems
gems: [jekyll-paginate]

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'codehilite'
    # span:
    #   line_numbers: false
    block:
      line_numbers: true
      start_line: 1
