# Setup
permalink: pretty
markdown: kramdown
timezone: Europe/London
# relative_permalinks: true
title:            Digital Publisher Guide
tagline:          'Help for publishers and students of publishing'
description:      'tutorials and screencasts about digital publishing and eBook Production'
url:              https://publisha.github.io
baseurl: ''
twitter_username: pageboy
github_username:  pageboy
# permalink: /:categories/:title/

author:
  name:           'Chris Jennings'
  url:            https://twitter.com/pageboy


# Custom vars
version:          0.2.0

github:
  repo:           publisha.github.io

  # Gems
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap, jekyll-seo-tag]

paginate:         4
paginate_path: '/blog/page:num/'


kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'codehilite'
    # span:
    #   line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# so that we can make a page that orders by category

tag-list: [InDesign, HTML, CSS, Using GitHub]

categories-list: [InDesign, "HTML and CSS", Typography, Using GitHub, XML, ePub, iBooks Author]

# collections
collections:
  screencasts:
    output: true
    layout: screencast

  eBookPublishing:
    output: true
    title: 'eBook Publishing'
    description: 'Workflow and techniques for designing, creating and publishing eBooks'
    defaults:
      layout: book

  papers:
    output: true
    title: 'Articles and Conference papers'
    defaults:
      layout: paper

# for prose
prose:
  #rooturl: '_posts'
  siteurl: 'https://publisha.github.io'
  # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'images'
  ignore:
    - README.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_site
    - LICENSE.md
    - atom.xml
    - _mdwriter.cson
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Choose Categories"
          options:
            - name: "InDesign"
              value: "InDsign"
            - name: "HTML"
              value: "HTML"
            - name: "CSS"
              value: "CSS"
            - name: "Typography"
              value: "Typography"
            - name: "Using GitHub"
              value: "Using GitHub"
    pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
