# Setup
permalink: pretty
markdown: kramdown
timezone: Europe/London
# relative_permalinks: true
title: Digital Publishing Hub
tagline: "Help for publishers and students of publishing"
description: "Tutorials and screencasts about digital publishing and eBook Production"
url: https://www.publisha.org
baseurl: ""
image: /images/homegallery/img_00127.jpg
twitter_username: pageboy
lang: en_gb
logo: https://www.publisha.org/images/publisha_logo.jpg
github_username: pageboy
flickr_key: 6a751024fcc480f70610ed1f98220880
flickr_id: 55648661@N00
# permalink: /:categories/:title/
includes:
  - public

# author:
#   name:           'Chris Jennings'
#   url:            https://twitter.com/pageboy
#

# Custom vars
version: 0.97

github:
  repo: publisha.github.io

  # Gems
plugins: [jekyll-paginate, jekyll-gist, jekyll-sitemap, jekyll-seo-tag]

paginate: 8
paginate_path: "/page:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: "codehilite"
    # span:
    #   line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# so that we can make a page that orders by category

tag-list: [InDesign, HTML, CSS, Using GitHub]

categories-list: [InDesign, HTML and CSS, Typography, XML, ePub]

# for Brookes

class-list: ["Design and Production", "Multi-Platform Publishing"]

# collections
collections:
  screencasts:
    output: true
    layout: screencast

  multi-platform-Publishing:
    output: true
    title: "Multi-platform Publishing"
    description: "Workflow and techniques for designing, creating and publishing for page and device"
    defaults:
      layout: book

  papers:
    output: true
    title: "Articles and Conference papers"
    defaults:
      layout: paper

  sections:
    output: true
    title: "Arranged by Topic"
    defaults:
      layout: page

  presentations:
    output: true
    title: "Presentations from Apple Keynote"
    defaults:
      layout: presentation
      excerpt_separator: <!--more-->

  galleries:
    output: true
    title: "Images from Flickr"
    defaults:
      layout: flickr

  eBooks:
    output: true
    title: "eBooks Created Here"
    defaults:
      layout: ebook
      excerpt_separator: <!--more-->
